### ISSUE TITLE
power button and keyboard

### ISSUE THREAD

**Issue by ghost** [nekr0z/linux-on-huawei-matebook-13-2019#1]
The power button should work when you keep pressing it in 1 second.

Touchpad log floods issue has been fixed in mainline kernel
https://patchwork.kernel.org/patch/10750063/

The keyboard switches are all works in my setup(arch+mainline kernel+deepin DE)
except Huawei key,but it do generate xev event

**Comment by nekr0z** [comment]
Thank you for hints! I've updated power button info and will test touchpad and keyboard switches further.

**Comment by nekr0z** [comment]
Updated touchpad information. Had to customize kernel patch for Debian, but things do work. Thanks again for your hint!

**Comment by nekr0z** [comment]
Got the keyboard working, added info. Thank you again for pushing me towards investigating this!
