### ISSUE TITLE
headphone jack  detection

### ISSUE THREAD

**Issue by ghost** [nekr0z/linux-on-huawei-matebook-13-2019#3]
Try this, it works for me.

> cat /etc/modprobe.d/sound.conf 
options snd_hda_intel model=dell-headset-multi

**Comment by nekr0z** [comment]
Yep, perfect. Adding to readme.

**Comment by shostakalex** [comment]
Hi there, thanks! Can I do something with my audio here? I've added before that line to sound.conf
```

[dreamndi@dreamndi-linlap modprobe.d]$ sudo alsactl restore
alsa-lib ucm_subs.c:252:(rval_lookup_main) Lookups are supported in v4+ syntax
alsa-lib parser.c:242:(error_node) UCM is not supported for this HDA model (HDA Intel PCH at 0x9421c000 irq 144)
alsa-lib main.c:1402:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -6
[dreamndi@dreamndi-linlap modprobe.d]$ alsactl restore
alsactl: state_lock:129: file /var/lib/alsa/asound.state lock error: Permission denied
alsactl: load_state:1636: Cannot open /var/lib/alsa/asound.state for reading: Permission denied
alsa-lib ucm_subs.c:252:(rval_lookup_main) Lookups are supported in v4+ syntax
alsa-lib parser.c:242:(error_node) UCM is not supported for this HDA model (HDA Intel PCH at 0x9421c000 irq 144)
alsa-lib main.c:1402:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -6
Found hardware: "HDA-Intel" "Realtek ALC256" "HDA:10ec0256,19e5320d,00100002 HDA:8086280b,80860101,00100000" "0x19e5" "0x3e09"
Hardware is initialized using a generic method

```

UPD: rebooted and autodetection works. Nice, thanks!

**Comment by frusanov** [comment]
On AMD version of MateBook 13 combo jack start work properly only after adding `options snd-hda-intel model=alc255-acer,dell-headset-multi` to my /etc/modprobe.d/sound.conf

I get it from https://bbs.archlinux.org/viewtopic.php?pid=1964401#p1964401

**Comment by nekr0z** [comment]
@frusanov Interesting! Care to make a pull request with this info?

**Comment by frusanov** [comment]
@nekr0z yes, I can. Can you check does same config work on intel version? I think better add to instruction one universal config

**Comment by nekr0z** [comment]
> Can you check does same config work on intel version?

@frusanov Not these days, unfortunately. I'm at a hospital with a bad case of Covid (I'm better already, so it'll be OK), here I'm stuck with the only earphones I have with me, and this model has no microphone, so I have no way of checking that the headset's microphone is detected and working.

If no one checks before I get home (hopefully in a week or two, though you never know), I'll check myself with a microphone-capable headset and let you know.

**Comment by frusanov** [comment]
A speedy recovery! 

I create PR where I determined info about amd version separately, but in case if on intel version same code also works it's needs to be corrected to one single recommendation

**Comment by nekr0z** [comment]
I'm merging it, and will test the Intel model and revisit the topic as soon as feasible.

**Comment by nekr0z** [comment]
I finally tested this extensively, and the `alc255-acer` variant works better with original Matebook 13 as well: the headset microphone detection works (with some particularities, but it didn't work at all with the original options line). I've made it a default now, no need for a separate option for AMD versions, indeed. Thanks again, @frusanov !

**Comment by opr-sergey** [comment]
On of my matebook 14s, headphones doesnt work after adding options `snd-hda-intel model=alc255-acer,dell-headset-multi` to my `/etc/modprobe.d/sound.conf`

I use apple headphones into jack 3.5mm, but play sound ONLY dynamics, at what microphone work correctly

**Comment by mil-ad** [comment]
@opr-sergey do the headphones work _before_ adding those options? 

there's a relevant lower-level [discussion](https://giters.com/thesofproject/linux/issues/3350) on sof
