### ISSUE TITLE
Compatibility with Matebook D 14 AMD ?

### ISSUE THREAD

**Issue by Emadmasroor** [nekr0z/linux-on-huawei-matebook-13-2019#35]
I have Ubuntu installed on my Huawei Matebook D 14 (with AMD Ryzen processor). Do you think this method will work on the BIOS [provided for this laptop](https://consumer.huawei.com/en/support/laptops/matebook-d-14-amd/)? Is there anything I should be aware of before trying it out?

**Comment by nekr0z** [comment]
I think the general approach should be mostly the same, at least it looks like the BIOS is provided in the same way that newer (i.e. ver. 1.28) BIOS for Matebook 13 is. Obviously, the `device-guid` and the filenames will be different.

> Is there anything I should be aware of before trying it out?

That it has not been tested, that things can go wrong and you may end up with an unbootable laptop, and that you'll only have yourself to blame if that happens. ;)
